(part "MAX3267CSA+"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "N.C.") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "FILTER") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT-") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "MAX3267CSA+")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "The MAX3266 is a transimpedance preamplifier for 1.25Gbps local area network (LAN) fiber optic receivers. The circuit features 200nA input-referred noise, 920MHz bandwidth, and 1mA input overload.")
    (property "Datasheet_Link" "https://www.analog.com/media/en/technical-documentation/data-sheets/MAX3266-MAX3267.pdf")
    (property "symbolName1" "MAX3267CSA+")
)
